# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/partcad/pre-commit
    rev: v1.8.2
    hooks:
      - id: prepare-commit-msg
        args: ["--open-source", "--commit-msg-filename"]
      - id: keep-a-changelog
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: check-yaml
      - id: check-added-large-files
      # https://github.com/docker/for-mac/issues/5029
      # - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          [
            "--format=requirements.txt",
            "--output=.devcontainer/requirements.txt",
          ]
      - id: poetry-install
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
